routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DeviceController;
use App\Http\Controllers\ParamController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/home/{device}/{type}', [HomeController::class, 'type'])->name('home.type');

Route::resource('devices', DeviceController::class);
Route::get('devices/{device}/data', [DeviceController::class, 'data'])->name('devices.data');
Route::get('devices/{device}/data-json', [DeviceController::class, 'dataJson'])->name('devices.data-json');

Route::resource('params', ParamController::class);

app/Models/Param.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Param extends Model
{
    use HasFactory;

    protected $table = 'params';

    public function getStatusLabelAttribute()
    {
        if ($this->status == 1) {
            return 'Active';
        } elseif ($this->status == 2) {
            return 'Inactive';
        } else {
            return '';
        }
    }
}

app/Http/Controllers/API/ParamController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Device;
use App\Models\Param;

class ParamController extends Controller
{
    public function index(Request $request, $appid = '', $appsecret = '')
    {
        $device = Device::where('appid', $appid)
                        ->where('appsecret', $appsecret)
                        ->first();

        if ($device) {
            $data = Param::select(['name', 'value'])
                         ->where('created_by', $device->created_by)
                         ->where('status', 1)
                         ->orderBy('id', 'desc')
                         ->get();

            return response()->json($data, 200);
        }
        
        return response()->json([
            'message' => 'Device is not found!'
        ], 404);
    }
}

app/Http/Controllers/ParamController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;

use App\Http\Requests\StoreParamRequest;
use App\Http\Requests\UpdateParamRequest;
use App\Models\Param;

class ParamController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $user = Auth::user();
        $records = Param::where('created_by', $user->id)
                        ->orderBy('id', 'desc')
                        ->get();

        return view('param.index', [
            'records' => $records
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('param.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreParamRequest $request)
    {
        $user = Auth::user();

        $record = new Param;
        $record->name = $request->name;
        $record->value = $request->value;
        $record->status = $request->status;
        $record->created_by = $user->id;
        $record->save();

        return redirect(route('params.index'))->with('status', 'New param has been added!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Param $param)
    {
        $user = Auth::user();
        if ($param->created_by != $user->id) {
            return abort(404);
        }

        return view('param.show', [
            'record' => $param
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Param $param)
    {
        $user = Auth::user();
        if ($param->created_by != $user->id) {
            return abort(404);
        }

        return view('param.edit', [
            'record' => $param
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateParamRequest $request, Param $param)
    {
        $param->name = $request->name;
        $param->value = $request->value;
        $param->status = $request->status;
        $param->save();

        return redirect(route('params.index'))->with('status', 'Param has been updated!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Param $param)
    {
        $user = Auth::user();
        if ($param->created_by != $user->id) {
            return response()->json([
                'message' => 'Param is not found!'
            ], 404);
        }

        $param->delete();
        return response()->json([
            'message' => 'Param has been deleted!'
        ], 200);
    }
}

resources/views/param/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <form action="{{route('params.store')}}" method="post">
                @csrf
                <div class="card">
                    <div class="card-header">{{ __('Add Param') }}</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Name" required>
                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Value</label>
                                    <input type="text" name="value" class="form-control @error('value') is-invalid @enderror" placeholder="Value" required>
                                    @error('value')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Status</label>
                                    <select name="status" class="form-control @error('name') is-invalid @enderror" placeholder="Status" required>
                                        <option value="">Choose Status</option>
                                        <option value="1">Active</option>
                                        <option value="2">Inactive</option>
                                    </select>
                                    @error('status')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <a href="{{route('params.index')}}" class="btn btn-secondary">Back</a>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/param/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <form action="{{route('params.update', $record->id)}}" method="post">
                @csrf
                @method('put')
                <input type="text" name="id" class="d-none" value="{{$record->id}}">
                <div class="card">
                    <div class="card-header">{{ __('Edit Param') }}</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{$record->name}}" placeholder="Name" required>
                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Value</label>
                                    <input type="text" name="value" class="form-control @error('value') is-invalid @enderror" value="{{$record->value}}" placeholder="Value" required>
                                    @error('value')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Status</label>
                                    <select name="status" class="form-control @error('name') is-invalid @enderror" placeholder="Status" required>
                                        <option value="">Choose Status</option>
                                        <option value="1" @if($record->status == 1) selected @endif>Active</option>
                                        <option value="2" @if($record->status == 2) selected @endif>Inactive</option>
                                    </select>
                                    @error('status')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <a href="{{route('params.index')}}" class="btn btn-secondary">Back</a>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/param/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Params') }}</div>
                <div class="card-body" style="max-height: 80vh; overflow: auto;">
                    <div class="row gap-2">
                        <div class="col-md-12">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-12">
                            <a href="{{route('params.create')}}" class="btn btn-primary">Add Param</a>
                        </div>
                        <div class="col-md-12">
                            <table class="table table-bordered table-striped table-hover table-responsive">
                                <thead>
                                    <tr>
                                        <th class="text-center" width="5%">No.</th>
                                        <th>Name</th>
                                        <th>Value</th>
                                        <th>Status</th>
                                        <th class="text-center" width="20%">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        $i = 1;
                                    @endphp
                                    @forelse ($records as $record)    
                                        <tr>
                                            <td class="text-center">{{$i}}</td>
                                            <td>{{$record->name}}</td>
                                            <td>{{$record->value}}</td>
                                            <td>
                                                @if ($record->status == 1)
                                                    <span class="badge bg-success">{{$record->status_label}}</span>
                                                @elseif ($record->status == 2)
                                                    <span class="badge bg-danger">{{$record->status_label}}</span>
                                                @endif
                                            </td>
                                            <td>
                                                <div class="d-flex justify-content-center gap-2">
                                                    <a href="{{route('params.show', $record->id)}}" class="btn btn-sm btn-secondary">Show</a>
                                                    <a href="{{route('params.edit', $record->id)}}" class="btn btn-sm btn-dark">Edit</a>
                                                    <a href="javascript:;" class="btn btn-sm btn-danger" onclick="handleDelete({{$record->id}})">Delete</a>
                                                </div>
                                            </td>
                                        </tr>
                                        @php
                                            $i++;
                                        @endphp
                                    @empty
                                        <tr>
                                            <td colspan="99" class="text-center">No Data</td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    const handleDelete = (id) => {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            focusCancel: true,
            reverseButtons: true,
            showCancelButton: true,
            confirmButtonColor: '#dc3545',
            cancelButtonColor: '#6c757d',
            confirmButtonText: 'Delete',
            cancelButtonText: 'Cancel'
        }).then((result) => {
            if (result.isConfirmed) {
                axios.delete(`/params/${id}`)
                .then((res) => {
                    Swal.fire({
                        title: 'Success',
                        text: res.data.message,
                        icon: 'success',
                        showConfirmButton: false,
                        timer: 3000
                    }).then(() => {
                        window.location.reload();
                    });
                })
                .catch((err) => {
                    Swal.fire({
                        title: `${err.response.status} | ${err.response.statusText}`,
                        text: err.message,
                        icon: 'error',
                        showConfirmButton: false,
                        timer: 3000
                    });
                });
            }
        });
    }
</script>
@endsection

resources/views/param/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Show Param') }}</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" name="name" class="form-control" value="{{$record->name}}" placeholder="Name" readonly>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Value</label>
                                <input type="text" name="value" class="form-control" value="{{$record->value}}" placeholder="Value" readonly>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Status</label>
                                <input type="text" name="status" class="form-control" value="{{$record->status_label}}" placeholder="Status" readonly>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between">
                    <a href="{{route('params.index')}}" class="btn btn-secondary">Back</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection