routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DeviceController;
use App\Http\Controllers\ParamController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/home/{device}/{type}', [HomeController::class, 'type'])->name('home.type');

Route::resource('devices', DeviceController::class);
Route::get('devices/{device}/data', [DeviceController::class, 'data'])->name('devices.data');
Route::get('devices/{device}/data-json', [DeviceController::class, 'dataJson'])->name('devices.data-json');

Route::resource('params', ParamController::class);

app/Models/Device.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Device extends Model
{
    use HasFactory;

    protected $table = 'devices';

    public function getWebhookAttribute()
    {
        return url("/api/webhook/{$this->appid}/{$this->appsecret}");
    }

    public static function generateappid()
    {
        $result = '';
        $repeat = true;
        while ($repeat) {
            $result = strtoupper(Str::random(8));
            $record = self::where('appid', $result)->first();
            if (is_null($record)) {
                $repeat = false;
            }
        }

        return $result;
    }

    public static function generateappsecret()
    {
        $result = '';
        $repeat = true;
        while ($repeat) {
            $result = strtoupper(Str::random(16));
            $record = self::where('appsecret', $result)->first();
            if (is_null($record)) {
                $repeat = false;
            }
        }

        return $result;
    }

    public function data()
    {
        return $this->hasMany(DeviceData::class, 'device_id');
    }
}

app/Http/Controllers/DeviceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;

use Illuminate\Http\Request;
use App\Http\Requests\StoreDeviceRequest;
use App\Http\Requests\UpdateDeviceRequest;
use App\Models\Device;

class DeviceController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $user = Auth::user();
        $records = Device::where('created_by', $user->id)
                         ->orderBy('id', 'desc')
                         ->get();

        return view('device.index', [
            'records' => $records
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('device.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreDeviceRequest $request)
    {
        $user = Auth::user();

        $record = new Device;
        $record->name = $request->name;
        $record->appid = Device::generateappid();
        $record->appsecret = Device::generateappsecret();
        $record->created_by = $user->id;
        $record->save();

        return redirect(route('devices.index'))->with('status', 'New device has been added!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Device $device)
    {
        $user = Auth::user();
        if ($device->created_by != $user->id) {
            return abort(404);
        }

        return view('device.show', [
            'record' => $device
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Device $device)
    {
        $user = Auth::user();
        if ($device->created_by != $user->id) {
            return abort(404);
        }

        return view('device.edit', [
            'record' => $device
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateDeviceRequest $request, Device $device)
    {
        $device->name = $request->name;
        $device->save();

        return redirect(route('devices.index'))->with('status', 'Device has been updated!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Device $device)
    {
        $user = Auth::user();
        if ($device->created_by != $user->id) {
            return response()->json([
                'message' => 'Device is not found!'
            ], 404);
        }

        $device->delete();
        return response()->json([
            'message' => 'Device has been deleted!'
        ], 200);
    }

    public function data(Device $device)
    {
        $user = Auth::user();
        if ($device->created_by != $user->id) {
            return abort(404);
        }

        return view('device.data', [
            'device' => $device
        ]);
    }

    public function dataJson(Request $request, Device $device)
    {
        $limit = $request->limit ? (int)$request->limit : 10;
        $offset = $request->offset ? (int)$request->offset : 0;

        $user = Auth::user();
        if ($device->created_by != $user->id) {
            return response()->json([
                'message' => 'Device is not found!'
            ], 404);
        }

        return response()->json([
            'data' => $device->data()->orderBy('id', 'desc')->limit($limit)->offset($offset)->get()
        ], 200);
    }
}

resources/views/device/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <form action="{{route('devices.store')}}" method="post">
                @csrf
                <div class="card">
                    <div class="card-header">{{ __('Add Device') }}</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Name" required>
                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <a href="{{route('devices.index')}}" class="btn btn-secondary">Back</a>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/device/data.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{$device->name}}</div>
                <div class="card-body" style="max-height: 80vh; overflow: auto;">
                    <div class="row gap-2">
                        <div class="col-md-12">
                            <table class="table table-bordered table-striped table-hover table-responsive">
                                <thead>
                                    <tr>
                                        <th class="text-center" width="5%">No.</th>
                                        <th>Body</th>
                                        <th>Date</th>
                                    </tr>
                                </thead>
                                <tbody id="tbody">
                                    <tr id="trEmpty">
                                        <td colspan="99" class="text-center">No Data</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="col-md-12 text-center">
                            <button id="btnLoad" type="button" class="btn btn-primary" onclick="loadmore()">Load More</button>
                        </div>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between">
                    <a href="{{route('devices.index')}}" class="btn btn-secondary">Back</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    let limit = 10;
    let offset = 0;

    window.onload = function() {
        loadmore();
    }

    const toggleloading = (value) => {
        const button = document.getElementById('btnLoad');
        button.disabled = value;
        if (value) {
            button.innerText = 'Loading';
        } else {
            button.innerText = 'Load More';
        }
    }

    const removebuttonloading = () => {
        const button = document.getElementById('btnLoad');
        button.parentNode.remove();
    }

    const removetrempty = () => {
        const trEmpty = document.getElementById('trEmpty');
        if (trEmpty !== null) {
            trEmpty.remove();
        }
    }

    const loadmore = () => {
        toggleloading(true);
        axios.get("{{route('devices.data-json', $device->id)}}", {
            params: {
                limit: limit,
                offset: offset
            }
        })
        .then((res) => {
            const records = res.data.data;
            if (records.length) {
                removetrempty();
            }

            records.forEach(record => {
                const tbody = document.getElementById('tbody');
                const no = tbody.children.length+1;

                const tr = document.createElement('tr');
                const tdNo = document.createElement('td');
                tdNo.classList.add('text-center');
                tdNo.appendChild(document.createTextNode(no));
                const tdBody = document.createElement('td');
                tdBody.appendChild(document.createTextNode(record.body));
                const tdDate = document.createElement('td');
                const createdAt = new Date(record.created_at);
                tdDate.appendChild(document.createTextNode(moment(createdAt).format('D/MM/y hh:mm:ss')));
                tr.appendChild(tdNo);
                tr.appendChild(tdBody);
                tr.appendChild(tdDate);
                tbody.appendChild(tr);

                offset++;
                toggleloading(false);
            });

            if (records.length < limit) {
                removebuttonloading();
            }
        })
        .catch((err) => {
            Swal.fire({
                title: `${err.response.status} | ${err.response.statusText}`,
                text: err.message,
                icon: 'error',
                showConfirmButton: false,
                timer: 3000
            });
        });
    }
</script>
@endsection

resources/views/device/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <form action="{{route('devices.update', $record->id)}}" method="post">
                @csrf
                @method('put')
                <input type="text" name="id" class="d-none" value="{{$record->id}}">
                <div class="card">
                    <div class="card-header">{{ __('Edit Device') }}</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4 mb-4">
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{$record->name}}" placeholder="Name" required>
                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-4 mb-4">
                                <div class="form-group">
                                    <label>APPID</label>
                                    <input type="text" name="appid" class="form-control" value="{{$record->appid}}" readonly>
                                </div>
                            </div>
                            <div class="col-md-4 mb-4">
                                <div class="form-group">
                                    <label>APPSECRET</label>
                                    <input type="text" name="appsecret" class="form-control" value="{{$record->appsecret}}" readonly>
                                </div>
                            </div>
                            <div class="col-md-12 mb-4">
                                <div class="form-group">
                                    <label>Webhook</label>
                                    <input type="text" name="webhook" class="form-control" value="{{$record->webhook}}" readonly>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <a href="{{route('devices.index')}}" class="btn btn-secondary">Back</a>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/device/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Devices') }}</div>
                <div class="card-body" style="max-height: 80vh; overflow: auto;">
                    <div class="row gap-2">
                        <div class="col-md-12">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-12">
                            <a href="{{route('devices.create')}}" class="btn btn-primary">Add Device</a>
                        </div>
                        <div class="col-md-12">
                            <table class="table table-bordered table-striped table-hover table-responsive">
                                <thead>
                                    <tr>
                                        <th class="text-center" width="5%">No.</th>
                                        <th>Name</th>
                                        <th>Webhook</th>
                                        <th>Data</th>
                                        <th class="text-center" width="20%">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        $i = 1;
                                    @endphp
                                    @forelse ($records as $record)    
                                        <tr>
                                            <td class="text-center">{{$i}}</td>
                                            <td>{{$record->name}}</td>
                                            <td>{{$record->webhook}}</td>
                                            <td><a href="{{route('devices.data', $record->id)}}">{{$record->data->count()}}</a> received</td>
                                            <td>
                                                <div class="d-flex justify-content-center gap-2">
                                                    <a href="{{route('devices.show', $record->id)}}" class="btn btn-sm btn-secondary">Show</a>
                                                    <a href="{{route('devices.edit', $record->id)}}" class="btn btn-sm btn-dark">Edit</a>
                                                    <a href="javascript:;" class="btn btn-sm btn-danger" onclick="handleDelete({{$record->id}})">Delete</a>
                                                </div>
                                            </td>
                                        </tr>
                                        @php
                                            $i++;
                                        @endphp
                                    @empty
                                        <tr>
                                            <td colspan="99" class="text-center">No Data</td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    const handleDelete = (id) => {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            focusCancel: true,
            reverseButtons: true,
            showCancelButton: true,
            confirmButtonColor: '#dc3545',
            cancelButtonColor: '#6c757d',
            confirmButtonText: 'Delete',
            cancelButtonText: 'Cancel'
        }).then((result) => {
            if (result.isConfirmed) {
                axios.delete(`/devices/${id}`)
                .then((res) => {
                    Swal.fire({
                        title: 'Success',
                        text: res.data.message,
                        icon: 'success',
                        showConfirmButton: false,
                        timer: 3000
                    }).then(() => {
                        window.location.reload();
                    });
                })
                .catch((err) => {
                    Swal.fire({
                        title: `${err.response.status} | ${err.response.statusText}`,
                        text: err.message,
                        icon: 'error',
                        showConfirmButton: false,
                        timer: 3000
                    });
                });
            }
        });
    }
</script>
@endsection

resources/views/device/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Show Device') }}</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4 mb-4">
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" name="name" class="form-control" value="{{$record->name}}" placeholder="Name" readonly>
                            </div>
                        </div>
                        <div class="col-md-4 mb-4">
                            <div class="form-group">
                                <label>APPID</label>
                                <input type="text" name="appid" class="form-control" value="{{$record->appid}}" readonly>
                            </div>
                        </div>
                        <div class="col-md-4 mb-4">
                            <div class="form-group">
                                <label>APPSECRET</label>
                                <input type="text" name="appsecret" class="form-control" value="{{$record->appsecret}}" readonly>
                            </div>
                        </div>
                        <div class="col-md-12 mb-4">
                            <div class="form-group">
                                <label>Webhook</label>
                                <input type="text" name="webhook" class="form-control" value="{{$record->webhook}}" readonly>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between">
                    <a href="{{route('devices.index')}}" class="btn btn-secondary">Back</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection